urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from . import views

app_name = 'standings-requests'

local_urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^request_pilot_standings/(?P<character_id>\d+)/', views.request_pilot_standings,
        name='request_pilot_standing'),
    url(r'^remove_pilot_standings/(?P<character_id>\d+)/', views.remove_pilot_standings,
        name='remove_pilot_standing'),
    url(r'^request_corp_standings/(?P<corp_id>\d+)/', views.request_corp_standings,
        name='request_corp_standing'),
    url(r'^remove_corp_standings/(?P<corp_id>\d+)/', views.remove_corp_standings,
        name='remove_corp_standing'),

    url(r'^view/pilots/$', views.view_pilots_standings, name='view_pilots'),
    url(r'^view/pilots/json/$', views.view_pilots_standings_json, name='view_pilots_json'),
    url(r'^view/pilots/download/$', views.download_pilot_standings, name='download_pilots'),
    url(r'^view/corps/$', views.view_groups_standings, name='view_groups'),
    url(r'^view/corps/json$', views.view_groups_standings_json, name='view_groups_json'),
    url(r'^manage/$', views.manage_standings, name='manage'),
    url(r'^manage/requests/$', views.manage_get_requests_json, name='manage_get_requests_json'),
    # Should always follow the path of the GET path above
    url(r'^manage/requests/(?P<contact_id>\d+)/$', views.manage_requests_write, name='manage_requests_write'),
    url(r'^manage/revocations/$', views.manage_get_revocations_json, name='manage_get_revocations_json'),
    url(r'^manage/revocations/(?P<contact_id>\d+)/$', views.manage_revocations_write,
        name='manage_get_revocations_write'),
    url(r'^manage/revocations/(?P<contact_id>\d+)/undo/$', views.manage_revocations_undo,
        name='manage_get_revocations_undo'),

    url(r'^view/requests/$', views.view_active_requests, name='view_requests'),
    url(r'^view/requests/json/$', views.view_active_requests_json, name='view_requests_json'),
    url(r'^manage/setuptoken/$', views.view_auth_page, name='view_auth_page'),
    url(r'^requester_add_scopes/$', views.view_requester_add_scopes, name='view_requester_add_scopes')
]

urlpatterns = [
    url(r'^standings-requests/', include((local_urlpatterns, 'standings-requests'))),
]

templates/standings-requests/error.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Standings Tool {% endblock %}

{% block page_title %}Request Standings{% endblock page_title %}
{% block extra_css %}

{% endblock extra_css %}

{% block content %}
    {% include 'standings-requests/partials/_menu.html' %}
    <div class="col-lg-12 container">
        <div class="panel panel-danger">
          <div class="panel-heading">{% trans "An Error Occurred" %}</div>
          <div class="panel-body">
              {{ error_message }}
          </div>
        </div>
    </div>
{% endblock content %}

{% block extra_script %}
{% endblock extra_script %}

templates/standings-requests/manage.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Standings Tool {% endblock %}

{% block page_title %}Request Standings{% endblock page_title %}
{% block extra_css %}
{% include "standings-requests/bundles/angular.html" %}
{% endblock extra_css %}

{% block content %}
    {% include 'standings-requests/partials/_menu.html' %}
    <div ng-app="standingsApp" ng-controller="ManageStandingsController">
        <error-messages></error-messages>
        <!-- Requests -->
        <div class="col-lg-12 container">
            <h2 style="margin-top:0;">{% trans "Requests" %}</h2>
            <div class="col-lg-12 container">
                <div class="row">
                    <div class="table-responsive">
                        <table class="table table-condensed table-hover table-striped">
                            <tr>
                                <th class="col-md-2">{% trans "Contact Name" %}</th>
                                <th class="col-md-2">{% trans "Corporation" %}</th>
                                <th class="col-md-2">{% trans "Alliance" %}</th>
                                <th class="col-md-2">{% trans "Main Character" %}</th>
                                <th class="col-md-1">{% trans "Scopes" %}</th>
                                <th class="col-md-1">{% trans "State" %}</th>
                                <th class="col-md-1" title="Reject and delete this standings request">{% trans "Reject" %}</th>
                                <th class="col-md-1" title="Standings change has been made in game">{% trans "Actioned" %}</th>
                            </tr>
                            {% verbatim %}
                            <tr ng-repeat="contact in requests">
                                <td>
                                    <clipboard-copy copy="contact.contact_name"></clipboard-copy>
                                </td>
                                <td>
                                    <span ng-show="contact.corporation_ticker">
                                        [{{ contact.corporation_ticker }}] {{ contact.corporation_name }}
                                    </span>
                                </td>
                                <td>
                                    <span ng-show="contact.alliance_name" ng-bind="contact.alliance_name"></span>
                                </td>
                                <td>
                                    <span ng-show="contact.main_character_ticker">
                                        [{{ contact.main_character_ticker }}] {{ contact.main_character_name }}
                                    </span>
                                </td>
                                <td>
                                    <bool-checkmark value="contact.has_scopes" true-title="Has required scopes" false-title="Missing Scopes add then using Add Scopes"></bool-checkmark>
                                </td>
                                <td>
                                    {{contact.state}}
                                </td>
                                <td>
                                    <span style="font-size:1.5em; cursor: pointer;" title="Reject" ng-click="rejectRequest(contact)">
                                        <i class="fa fa-thumbs-o-down" aria-hidden="true"></i>
                                    </span>
                                </td>
                                <td>
                                    <span style="font-size:1.5em; color:#0006BA; cursor: pointer;" ng-click="actionRequest(contact)" title="Standing Set">
                                        <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                                    </span>
                                </td>
                            </tr>
                            {% endverbatim %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- Revocations -->
        <div class="col-lg-12 container">
            <h2 style="margin-top:0;">{% trans "Revocations" %}</h2>
            <div class="col-lg-12 container">
                <div class="row">
                    <div class="table-responsive">
                        <table class="table table-condensed table-hover table-striped">
                            <tr>
                                <th class="col-md-2">{% trans "Contact Name" %}</th>
                                <th class="col-md-1">{% trans "Corporation" %}</th>
                                <th class="col-md-1">{% trans "Alliance" %}</th>
                                <th class="col-md-2">{% trans "Main Character" %}</th>
                                <th class="col-md-2">{% trans "Scopes" %}</th>
                                <th class="col-md-1">{% trans "State" %}</th>
                                <th class="col-md-1" title="Delete this standings request. Standing will become unmanaged">{% trans "Delete" %}</th>
                                <th class="col-md-1" title="Undo this standings revocation and generate a new standings request">{% trans "Undo" %}</th>
                                <th class="col-md-1" title="Standings change has been made in game">{% trans "Actioned" %}</th>
                            </tr>
                            {% verbatim %}
                            <tr ng-repeat="contact in revocations">
                                <td>
                                    <clipboard-copy copy="contact.contact_name"></clipboard-copy>
                                </td>
                                <td>
                                    <span ng-show="contact.corporation_ticker">
                                        [{{ contact.corporation_ticker }}] {{ contact.corporation_name }}
                                    </span>
                                </td>
                                <td>
                                    <span ng-show="contact.alliance_name" ng-bind="contact.alliance_name"></span>
                                </td>
                                <td>
                                    <span ng-show="contact.main_character_ticker">
                                        [{{ contact.main_character_ticker }}] {{ contact.main_character_name }}
                                    </span>
                                </td>
                                <td>
                                    <bool-checkmark value="contact.has_scopes" true-title="Has required scopes" false-title="Missing Scopes add then using Add Scopes"></bool-checkmark>
                                </td>
                                <td>
                                    {{contact.state}}
                                </td>
                                <td>
                                    <span style="font-size:1.5em; cursor: pointer;" title="Delete" ng-click="deleteRevocation(contact)">
                                        <i class="fa fa-times" aria-hidden="true"></i>
                                    </span>
                                </td>
                                <td>
                                    <span style="font-size:1.5em; cursor: pointer;" title="Undo" ng-click="undoRevocation(contact)">
                                        <i class="fa fa-undo" aria-hidden="true"></i>
                                    </span>
                                </td>
                                <td>
                                    <span style="font-size:1.5em; color:#575757; cursor: pointer;" title="Standing Set" ng-click="actionRevocation(contact)">
                                        <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                                    </span>
                                </td>
                            </tr>
                            {% endverbatim %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_javascript %}
    <script type="text/javascript">
        {% include 'standings-requests/partials/_angular_urls.html' %}
    </script>
    <script src="{% static 'standings-requests/app.js' %}"></script>
    <script src="{% static 'standings-requests/error.js' %}"></script>
    <script src="{% static 'standings-requests/standings_filter.js' %}"></script>
    <script src="{% static 'standings-requests/manage.js' %}"></script>
{% endblock extra_javascript %}

templates/standings-requests/requester_added_scopes.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Standings Tool {% endblock %}

{% block page_title %}Request Standings{% endblock page_title %}
{% block extra_css %}
{% include "standings-requests/bundles/angular.html" %}
{% endblock extra_css %}
{% block content %}
    {% include 'standings-requests/partials/_menu.html' %}
    <div class="alert alert-success" role="alert">
    Successfully added token with scopes {% for scope in scopes %}{%if not forloop.first %}, {% endif %}{{scope}}{% endfor %} for {{char_name}}.
    </div>
{% endblock %}
{% block extra_javascript %}
    <script type="text/javascript">
        {% include 'standings-requests/partials/_angular_urls.html' %}
    </script>
{% endblock extra_javascript %}

templates/standings-requests/requests.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Standings Tool {% endblock %}

{% block page_title %}Request Standings{% endblock page_title %}
{% block extra_css %}
{% include "standings-requests/bundles/angular.html" %}
{% endblock extra_css %}

{% block content %}
    {% include 'standings-requests/partials/_menu.html' %}
    <div ng-app="standingsApp" ng-controller="ViewRequestsController">
        <error-messages></error-messages>
        <!-- Requests -->
        <div class="col-lg-12 container">
            <h2 style="margin-top:0;">{% trans "Requests" %}</h2>
            <div class="col-lg-12 container">
                <div class="row">
                    <div class="table-responsive">
                        <table class="table table-condensed table-hover table-striped">
                            <tr>
                                <th class="col-md-2">{% trans "Contact Name" %}</th>
                                <th class="col-md-1">{% trans "Corporation" %}</th>
                                <th class="col-md-1">{% trans "Alliance" %}</th>
                                <th class="col-md-1">{% trans "Type" %}</th>
                                <th class="col-md-2">{% trans "Main Character" %}</th>
                                <th class="col-md-1">{% trans "Scopes" %}</th>
                                <th class="col-md-1">{% trans "State" %}</th>
                                <th class="col-md-1">{% trans "Actioned" %}</th>
                                <th class="col-md-1">{% trans "Effective" %}</th>
                                <th class="col-md-1" title="Reject and delete this standings request">{% trans "Reject" %}</th>
                            </tr>
                            {% verbatim %}
                            <tr ng-repeat="contact in requests">
                                <td>
                                    <clipboard-copy copy="contact.contact_name"></clipboard-copy>
                                </td>
                                <td>
                                    <span ng-show="contact.corporation_ticker">
                                        [{{ contact.corporation_ticker }}] {{ contact.corporation_name }}
                                    </span>
                                </td>
                                <td>
                                    <span ng-show="contact.alliance_name" ng-bind="contact.alliance_name"></span>
                                </td>
                                <td>
                                    <span ng-show="contact.is_corp">Corp</span>
                                    <span ng-show="contact.is_pilot">Pilot</span>
                                </td>
                                <td>
                                    <span ng-show="contact.main_character_ticker">
                                        [{{ contact.main_character_ticker }}] {{ contact.main_character_name }}
                                    </span>
                                </td>
                                <td>
                                    <bool-checkmark value="contact.has_scopes" true-title="Has required scopes" false-title="Missing required scopes"></bool-checkmark>
                                </td>
                                <td>
                                    {{contact.state}}
                                </td>
                                <td>
                                    <span ng-bind="contact.action_by" ng-show="contact.actioned"></span>
                                </td>
                                <td>
                                    <bool-checkmark value="contact.effective" true-title="Standing Effective" false-title="Standing not effective"></bool-checkmark>
                                </td>
                                <td>
                                    <span style="font-size:1.5em; cursor: pointer;" title="Reject" ng-click="rejectRequest(contact)">
                                        <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
                                    </span>
                                </td>
                            </tr>
                            {% endverbatim %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_javascript %}
    <script type="text/javascript">
        {% include 'standings-requests/partials/_angular_urls.html' %}
    </script>
    <script src="{% static 'standings-requests/app.js' %}"></script>
    <script src="{% static 'standings-requests/error.js' %}"></script>
    <script src="{% static 'standings-requests/standings_filter.js' %}"></script>
    <script src="{% static 'standings-requests/manage.js' %}"></script>
    <script src="{% static 'standings-requests/requests.js' %}"></script>
{% endblock extra_javascript %}

templates/standings-requests/view_groups.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Standings Tool {% endblock %}

{% block page_title %}Request Standings{% endblock page_title %}
{% block extra_css %}
{% include "standings-requests/bundles/angular.html" %}
{% endblock extra_css %}

{% block content %}
    {% include 'standings-requests/partials/_menu.html' %}
    <div ng-app="standingsApp" ng-controller="GroupsListController">
        <standings-filter-controls></standings-filter-controls>
        <div class="col-lg-12 container">
            <h1 class="page-header">{% trans "Groups" %}</h1>
            <div class="pull-right">
                Last API Update: {{ lastUpdate | date:"SHORT_DATETIME_FORMAT" }}
            </div>
            <div class="col-lg-12 container">
                <div class="row">
                    <div class="table-responsive">
                        <table class="table table-condensed table-hover table-striped">
                            <tr>
                                <th class="col-md-3">{% trans "Corporation" %}</th>
                                <th class="col-md-1">{% trans "Standing" %}</th>
                                <th class="col-md-1">{% trans "Labels" %}</th>
                            </tr>
                            {% verbatim %}
                            <tr ng-repeat="entity in corps | filterStandings">
                                <td>
                                    <span ng-bind="entity.corporation_name"></span>
                                </td>
                                <td>
                                    <span style="font-size:1.5em;">
                                        <standings-icon standing="entity.standing"></standings-icon>
                                    </span>
                                </td>
                                <td>
                                    <span ng-repeat="label in entity.labels" ng-bind="label"></span>
                                </td>
                            </tr>
                            {% endverbatim %}
                            <tr>
                                <th class="col-md-3">{% trans "Alliance" %}</th>
                                <th class="col-md-1">{% trans "Standing" %}</th>
                                <th class="col-md-1">{% trans "Labels" %}</th>
                            </tr>
                            {% verbatim %}
                            <!-- Should DRY this -->
                            <tr ng-repeat="entity in alliances | filterStandings">
                                <td>
                                    <span ng-bind="entity.alliance_name"></span>
                                </td>
                                <td>
                                    <span style="font-size:1.5em;">
                                        <standings-icon standing="entity.standing"></standings-icon>
                                    </span>
                                </td>
                                <td>
                                    <span ng-repeat="label in entity.labels" ng-bind="label"></span>
                                </td>
                            </tr>
                            {% endverbatim %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_javascript %}
    <script type="text/javascript">
        {% include 'standings-requests/partials/_angular_urls.html' %}
    </script>
    <script src="{% static 'standings-requests/app.js' %}"></script>
    <script src="{% static 'standings-requests/standings_filter.js' %}"></script>
    <script src="{% static 'standings-requests/view_groups.js' %}"></script>
{% endblock extra_javascript %}

templates/standings-requests/view_pilots.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Standings Tool {% endblock %}

{% block page_title %}Request Standings{% endblock page_title %}
{% block extra_css %}
{% include "standings-requests/bundles/angular.html" %}
{% endblock extra_css %}

{% block content %}
    {% include 'standings-requests/partials/_menu.html' %}
    <div ng-app="standingsApp" ng-controller="PilotListController">
        <standings-filter-controls states="true" scopes="true"></standings-filter-controls>
        <div class="col-lg-12 container">
            <h1 class="page-header">
                {% trans "Pilots" %}
                {% if perms.standingstool.download %}
                <div class="pull-right"><a href="{% url "standings-requests:download_pilots" %}" class="btn btn-info">{% trans "Download" %}</a></div>
                {% endif %}
            </h1>
            <div class="pull-left">
                This data is cached for up to 10 minutes.<br/>
                Last API Update: {{ lastUpdate | date:"SHORT_DATETIME_FORMAT" }}
            </div>
            <div class="pull-right form-inline">
                <div class="form-group" style="padding-bottom:1.9em;">
                    <label for="userPageSize">Page size</label>
                    <select id="userPageSize" type="text" ng-model="pageSize" class="form-control" style="width:5em;">
                        <option value="10">10</option>
                        <option value="50" selected>50</option>
                        <option value="100">100</option>
                        <option value="500">500</option>
                        <option value="1000">1000</option>
                        <option value="">Everything</option>
                    </select>
                </div>
                <ul uib-pagination total-items="filteredStandings.length" ng-model="currentPage" max-size="5"
                    boundary-link-numbers="true" boundary-links="true" style="margin:0;"
                    items-per-page="pageSize"
                    previous-text="&lsaquo;" next-text="&rsaquo;" first-text="&laquo;" last-text="&raquo;"></ul>
            </div>
            <div class="col-lg-12 container">
                <div class="row">
                    <div class="table-responsive">
                        <table class="table table-condensed table-hover table-striped">
                            <tr>
                                <th class="col-md-2">{% trans "Character" %}</th>
                                <th class="col-md-2">{% trans "Corporation" %}</th>
                                <th class="col-md-2">{% trans "Alliance" %}</th>
                                <th class="col-md-2">{% trans "Main Character" %}</th>
                                <th class="col-md-1">{% trans "Standing" %}</th>
                                <th class="col-md-1">{% trans "Scopes" %}</th>
                                <th class="col-md-1">{% trans "State" %}</th>
                                <th class="col-md-1">{% trans "Labels" %}</th>
                            </tr>
                            {% verbatim %}
                            <tr ng-repeat="character in filteredStandings = (pilots | filterStandings) | limitTo : pageSize : (currentPage-1) * pageSize">
                                <td>
                                    <clipboard-copy copy="character.character_name"></clipboard-copy>
                                </td>
                                <td>
                                    <span ng-show="character.corporation_ticker">
                                        [{{ character.corporation_ticker }}]
                                    </span>
                                    <span ng-show="character.corporation_name">
                                        {{ character.corporation_name }}
                                    </span>
                                </td>
                                <td>
                                    <span ng-show="character.alliance_name" ng-bind="character.alliance_name"></span>
                                </td>
                                <td>
                                    <span ng-show="character.main_character_ticker">
                                        [{{ character.main_character_ticker }}]
                                    </span>
                                    <span ng-show="character.main_character_name">
                                        {{ character.main_character_name }}
                                    </span>
                                </td>
                                <td>
                                    <span style="font-size:1.5em;">
                                        <standings-icon standing="character.standing"></standings-icon>
                                    </span>
                                </td>
                                <td>
                                    <bool-checkmark value="character.has_required_scopes" true-title="Has required scopes" false-title="Missing required scopes"></bool-checkmark>
                                </td>
                                <td>
                                    {{character.state}}
                                </td>
                                <td>
                                    <span ng-repeat="label in character.labels" ng-bind="label"></span>
                                </td>
                            </tr>
                            {% endverbatim %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_javascript %}
    <script type="text/javascript">
        {% include 'standings-requests/partials/_angular_urls.html' %}
    </script>
    <script src="{% static 'standings-requests/app.js' %}"></script>
    <script src="{% static 'standings-requests/standings_filter.js' %}"></script>
    <script src="{% static 'standings-requests/view_pilots.js' %}"></script>
{% endblock extra_javascript %}

templates/standings-requests/view_sso.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Standings Tool {% endblock %}

{% block page_title %}Request Standings{% endblock page_title %}
{% block extra_css %}
{% include "standings-requests/bundles/angular.html" %}
{% endblock extra_css %}
{% block content %}
    {% include 'standings-requests/partials/_menu.html' %}
    {% if have_token %}
    <div class="alert alert-success" role="alert">Successfully setup token for {{char_name}} with character_id={{char_id}}</div>
    {% else %}
    <div class="alert alert-danger" role="alert">Failed to setup token for {{char_name}} with character_id={{char_id}} got token for {{token_char_name}} with character_id={{token_char_id}}</div>
    {% endif %}
{% endblock %}
{% block extra_javascript %}
    <script type="text/javascript">
        {% include 'standings-requests/partials/_angular_urls.html' %}
    </script>
{% endblock extra_javascript %}