urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from . import views

app_name = 'standings-requests'

local_urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^request_pilot_standings/(?P<character_id>\d+)/', views.request_pilot_standings,
        name='request_pilot_standing'),
    url(r'^remove_pilot_standings/(?P<character_id>\d+)/', views.remove_pilot_standings,
        name='remove_pilot_standing'),
    url(r'^request_corp_standings/(?P<corp_id>\d+)/', views.request_corp_standings,
        name='request_corp_standing'),
    url(r'^remove_corp_standings/(?P<corp_id>\d+)/', views.remove_corp_standings,
        name='remove_corp_standing'),

    url(r'^view/pilots/$', views.view_pilots_standings, name='view_pilots'),
    url(r'^view/pilots/json/$', views.view_pilots_standings_json, name='view_pilots_json'),
    url(r'^view/pilots/download/$', views.download_pilot_standings, name='download_pilots'),
    url(r'^view/corps/$', views.view_groups_standings, name='view_groups'),
    url(r'^view/corps/json$', views.view_groups_standings_json, name='view_groups_json'),
    url(r'^manage/$', views.manage_standings, name='manage'),
    url(r'^manage/requests/$', views.manage_get_requests_json, name='manage_get_requests_json'),
    # Should always follow the path of the GET path above
    url(r'^manage/requests/(?P<contact_id>\d+)/$', views.manage_requests_write, name='manage_requests_write'),
    url(r'^manage/revocations/$', views.manage_get_revocations_json, name='manage_get_revocations_json'),
    url(r'^manage/revocations/(?P<contact_id>\d+)/$', views.manage_revocations_write,
        name='manage_get_revocations_write'),
    url(r'^manage/revocations/(?P<contact_id>\d+)/undo/$', views.manage_revocations_undo,
        name='manage_get_revocations_undo'),

    url(r'^view/requests/$', views.view_active_requests, name='view_requests'),
    url(r'^view/requests/json/$', views.view_active_requests_json, name='view_requests_json'),
    url(r'^manage/setuptoken/$', views.view_auth_page, name='view_auth_page'),
    url(r'^requester_add_scopes/$', views.view_requester_add_scopes, name='view_requester_add_scopes')
]

urlpatterns = [
    url(r'^standings-requests/', include((local_urlpatterns, 'standings-requests'))),
]

templates/standings-requests/partials/_angular_urls.html
{% load staticfiles %}
var urls = {
    pilots_json: "{% url 'standings-requests:view_pilots_json' %}",
    groups_json: "{% url 'standings-requests:view_groups_json' %}",
    standings_icon_template: "{% static 'standings-requests/templates/standing.html' %}",
    standings_filter_controls_template: "{% static 'standings-requests/templates/standings_filters.html' %}",
    copy_field_template: "{% static 'standings-requests/templates/copy_field.html' %}",
    standings_requests_json_base: "{% url 'standings-requests:manage_get_requests_json' %}",
    standings_revocations_json_base: "{% url 'standings-requests:manage_get_revocations_json' %}",
    bool_tick_template: "{% static 'standings-requests/templates/bool_tick.html' %}",
    error_template: "{% static 'standings-requests/templates/error.html' %}",
    view_requests_json_base: "{% url 'standings-requests:view_requests_json' %}",
};

templates/standings-requests/partials/_menu.html
{% load i18n %}
{% load navactive %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">{% trans "Standings Tool" %}</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% if perms.standingsrequests.affect_standings %}
                <li class="{% navactive request 'standings-requests:view_auth_page' %}">
                    <a href="{% url 'standings-requests:view_auth_page' %}">{% trans "Setup Alliance Token" %}</a>
                </li>
                {% endif %}
                <li class="{% navactive request 'standings-requests:index' %}">
                    <a href="{% url 'standings-requests:index' %}">{% trans "Request Standings" %}</a>
                </li>
                {% if perms.standingsrequests.view %}
                <li class="{% navactive request 'standings-requests:view_pilots' %}">
                    <a href="{% url 'standings-requests:view_pilots' %}">{% trans "View Pilots Standings" %}</a>
                </li>
                <li class="{% navactive request 'standings-requests:view_groups' %}">
                    <a href="{% url 'standings-requests:view_groups' %}">{% trans "View Groups Standings" %}</a>
                </li>
                {% endif %}
                {% if perms.standingsrequests.affect_standings %}
                <li class="{% navactive request 'standings-requests:manage' %}">
                    <a href="{% url 'standings-requests:manage' %}">{% trans "Manage Requests" %}</a>
                </li>
                <li class="{% navactive request 'standings-requests:view_requests' %}">
                    <a href="{% url 'standings-requests:view_requests' %}">{% trans "View Requests" %}</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/standings-requests/partials/_standing.html
{% if standing < -5.0 %}
    <i class="fa fa-minus-square fa-fw grayiconecolor" style="color:#930404;" title="{{ standing }}"></i>
{% elif standing < 0.0 %}
    <i class="fa fa-minus-square fa-fw grayiconecolor" style="color:#c34704;" title="{{ standing }}"></i>
{% elif standing == 0.0 %}
    <i class="fa fa-bars fa-fw grayiconecolor" style="color:#878787;" title="{{ standing }}"></i>
{% elif standing <= 5.0 %}
    <i class="fa fa-plus-square fa-fw grayiconecolor" style="color:#2a64c3;" title="{{ standing }}"></i>
{% elif standing <= 10.0 %}
    <i class="fa fa-plus-square fa-fw grayiconecolor" style="color:#042177;" title="{{ standing }}"></i>
{% endif %}